### ISSUE TITLE
Fix CheckDoc issues

### ISSUE THREAD

**Issue by andyleejordan** [ocaml/caml-mode#2]
I am going through fixing _some_ of them, but some of the issues require explanation for functions that I am not yet qualified to explain.

This was spawned by https://github.com/melpa/melpa/pull/5966

**Comment by andschwa** [comment]
I would open a PR with my branch right now, but GitHub is currently degraded. I will try again soon.

**Comment by Chris00** [comment]
I [started doing it](https://github.com/ocaml/caml-mode/commit/b6eebe4943c8d561f4e7d5adf46602d029ef03e3) but there is still a lot! :-)
