### ISSUE TITLE
release tags?

### ISSUE THREAD

**Issue by treinen** [ocaml/caml-mode#6]
Hi,

Since caml-mode was separated from the ocaml mainline, the notion of a release was apperently lost. it would be helpful (for instance for people who create packages) if there were at least git tags that indicate what you consider to be release.

For debian, git tags are sufficient, no need to roll a release tarball.

Thanks -Ralf.

**Comment by monnier** [comment]
I'm looking at including caml-mode in the upcoming NonGNU ELPA archive and this seems to be a blocker (beside the deployment of NonGNU ELPA itself, obviously :-( ).
Ideally, for NonGNU ELPA, the package's version should be placed in the header of `caml.el`, next to the author and webpage as `Version: NN.MM`, such that the infrastructure will know to generate a new package when that line changes, e.g.:

    diff --git a/caml.el b/caml.el
    index 81c25c40..4c03944d 100644
    --- a/caml.el
    +++ b/caml.el
    @@ -7,7 +7,8 @@
     ;; Maintainer: Damien Doligez <damien.doligez@inria.fr>
     ;; Created: July 1993
     ;; Keywords: OCaml
    -;; Homepage: https://github.com/ocaml/ocaml/
    +;; Version: 4.7
    +;; Homepage: https://github.com/ocaml/caml-mode
     
     ;; This file is not part of GNU Emacs.
 
PS: I'd also be interested to hear positive confirmation that the maintainers of caml-mode would agree to distribute the mode via NonGNU ELPA (the license already allows it, of course, but if they don't like the idea, then I'd rather not invest time into it).

**Comment by Chris00** [comment]
@monnier I've updated the `caml.el` header.  I agree that putting caml-mode in NonGNU ELPA is a good thing.

**Comment by Chris00** [comment]
@treinen I'm on the verge of making a release (also in opam).

**Comment by Chris00** [comment]
The release tag 4.9 has been pushed.  A new OPAM package [is underway](https://github.com/ocaml/opam-repository/pull/19421).

**Comment by dbuenzli** [comment]
Thank you Christophe !
