### ISSUE TITLE
Missing definition of INSTALL_DATA in Makefile

### ISSUE THREAD

**Issue by StefanBruens** [ocaml/caml-mode#8]
INSTALL_DATA was moved to "../Makefile.common" 

https://github.com/ocaml/caml-mode/commit/2bc0b922ffcf498876f8c6ea14d99553dae8b7fa#diff-b67911656ef5d18c4ae36cb6741b7965

and later deleted without replacement:

https://github.com/ocaml/caml-mode/commit/1d6cd46e3e862dbb3dc20c5c78da892cf0794546#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by Chris00** [comment]
Thanks for reporting.  Fixed by 06c445b.
